general {
    before_sleep_cmd = ~/.config/sway/scripts/lock.sh
    after_sleep_cmd = brightnessctl --restore
}

listener {
    timeout = 300
    on-timeout = brightnessctl --save set 20%
    on-resume = brightnessctl --restore
}

listener {
    timeout = 600
    on-timeout = ~/.config/sway/scripts/lock.sh
}

listener {
    timeout = 900
    on-timeout = swaymsg "output * power off"
    on-resume = swaymsg "output * power on"
}
