#!/usr/bin/env bash

# Catppuccin Mocha: Blue for active, Surface0 for inactive
borders \
    active_color=0xff89b4fa \
    inactive_color=0xff313244 \
    width=5.0 \
    hidpi=on \
    style=round \
    blacklist="Raycast" \
    &
