general {
    before_sleep_cmd = ~/.config/niri/scripts/lock.sh
    after_sleep_cmd = brightnessctl --restore
}

listener {
    timeout = 180
    on-timeout = brightnessctl --save set 35%
    on-resume = brightnessctl --restore
}

listener {
    timeout = 600
    on-timeout = ~/.config/niri/scripts/lock.sh
}

listener {
    timeout = 900
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
