#!/bin/sh

swayidle -dw \
    timeout 100 "brightnessctl set 40%-" \
            resume "brightnessctl set +40%" \
    timeout 150 "pgrep swaylock || swaylock" \
    timeout 300 "hyprctl dispatch dpms off" \
			resume "hyprctl dispatch dpms on" \
    timeout 600 "systemctl suspend" \
            before-sleep "pgrep swaylock || swaylock"

