#!/usr/bin/env bash

lidstate="${1}"

mapfile -t monitors < <(hyprctl monitors all  hyprctl dispatch dpms off| grep "Monitor" | awk '{print $2}')

if [[ "${lidstate}" == "close" ]]; then
    if [[ ${#monitors[@]} -eq 1 && "${monitors[0]}" == "eDP-1" ]]; then
        #swaylock -f
        #hyprctl keyword monitor "eDP-1, disable"
        sleep 1
        systemctl suspend
    else
        hyprctl dispatch dpms off "eDP-1"
        hyprctl keyword monitor "eDP-1, disable"
    fi
fi

#if [[ "${lidstate}" == "open" ]]; then
    #hyprctl dispatch dpms on "eDP-1"
    #hyprctl keyword monitor "eDP-1, enable"
#fi

