#!/usr/bin/env bash

#hyprctl dispatch moveworkspacetomonitor 1 "$1"
#hyprctl dispatch workspace 1
#hyprctl dispatch moveworkspacetomonitor 3 "$1"

bash "${XDG_CONFIG_HOME}/hypr/scripts/waybar-dispatch"
