#!/usr/bin/env bash

swww img "${XDG_CONFIG_HOME}/hypr/wallpaper.png" --transition-type=fade --transition-duration=0.7

#hyprctl dispatch moveworkspacetomonitor 1 "$1"
#hyprctl dispatch workspace 1
#hyprctl dispatch moveworkspacetomonitor 3 "$1"

bash "${XDG_CONFIG_HOME}/hypr/scripts/waybar-dispatch"
