#!/usr/bin/env bash

set -eu

mapfile -t monitor_array < <(hyprctl monitors | grep "Monitor" | awk '{print $2}')

if [ ${#monitor_array[@]} -gt 1 ]; then
    for monitor in "${monitor_array[@]}"; do
        if [ "${monitor}" != "eDP-1" ]; then
            selected_monitor="${monitor}"
            break
        fi
    done
else
    selected_monitor="${monitor_array[0]}"
fi

if pgrep -x "waybar" > /dev/null; then
    pkill waybar
fi

hyprctl dispatch exec -- waybar -c "${XDG_CONFIG_HOME}/waybar/config-${selected_monitor}"
