#!/bin/bash

monitor_names=$(hyprctl monitors -j | jq -r '.[] | .name')
monitor_ids=$(hyprctl monitors -j | jq -r '.[] | .id')
workspace_start=01
hyprcmd=""
id=0

for monitor in $monitor_names; do
    workspace_end=$((workspace_start+4))
    default=",default:true"
    cmdbreak=";"
    
    for w in $(eval echo "{$workspace_start..$workspace_end}"); do
        hyprcmd=$hyprcmd"keyword workspace $w,monitor:$monitor$default$cmdbreak"
        default=""
    done

    workspace_start=$((workspace_start+10))
    id=$((id+1))
done

hyprctl --batch "$hyprcmd"

for i in $monitor_ids; do
    hyprctl dispatch workspace "${i}1"
done
