general {
    before_sleep_cmd = ~/.config/hypr/scripts/lock.sh
    after_sleep_cmd = brightnessctl --restore
}

listener {
    timeout = 180
    on-timeout = brightnessctl --save set 20%
    on-resume = brightnessctl --restore
}

listener {
    timeout = 600
    on-timeout = ~/.config/hypr/scripts/lock.sh
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
